# -*- coding: utf-8 -*-
"""IgM and PTMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZpswi6eSKpLS-IV9aV_MQqps7Jx5kn4

##**Pregunta biológica: ¿PTMs en epítopos B lineales que elicitan IgMs?**
En IEDB

### epitopos

## La frecuencia de epítopos con PTM en general
"""

import pandas as pd

df=pd.read_csv('everyone.csv')

df=df[['Epitope - Name']]

print('Estos son todos los epítopos que recoge IEDB:',(len(df)))

import re

# Función para encontrar secuencias con '+' o espacios
sequences_with_invalid_chars = df[df['Epitope - Name'].str.contains(r'[+\s]', na=False)]

# Mostrar las secuencias
print("Sequences with '+' or spaces:")
print(sequences_with_invalid_chars)

print('por lo tanto la proporción es de',(len(sequences_with_invalid_chars)/len(df))*100,'%')

"""##IgMs en todas las patologías"""

#En todas las patologías

pregunta= pd.read_csv('igm.csv')

pregunta= pregunta[['Epitope - Name']]

len(pregunta)

import re

# Función para encontrar secuencias con '+' o espacios
sequences_with_invalid_chars = df[df['Epitope - Name'].str.contains(r'[+\s]', na=False)]

# Mostrar las secuencias
print("Sequences with '+' or spaces:")
print(sequences_with_invalid_chars)

len(sequences_with_invalid_chars)

"""###IgM en infeccioso"""

import pandas as pd
df= pd.read_csv('igm-infec.csv')

df= df[['Epitope - Name']]

len(df)

import re

# Función para encontrar secuencias con '+' o espacios
sequences_with_invalid_chars = df[df['Epitope - Name'].str.contains(r'[+\s]', na=False)]

# Mostrar las secuencias
print("Sequences with '+' or spaces:")
print(sequences_with_invalid_chars)

len(sequences_with_invalid_chars)

(len(sequences_with_invalid_chars)/len(df))*100

"""### IgM en alergias"""

#únicamente hay 11 registros y ninguno con PTMs para qué descargarlo

"""###IgM en autoinmunes"""

df= pd.read_csv('igm-autoinmune.csv')

df= df[['Epitope - Name']]

len(df) #Número de epítopos totales

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Función para encontrar secuencias con '+' o espacios
sequences_with_invalid_chars = df[df['Epitope - Name'].str.contains(r'[+\s]', na=False)]

# Mostrar las secuencias
print("Sequences with '+' or spaces:")
print(sequences_with_invalid_chars)

print('por lo tanto la proporción es de',(len(sequences_with_invalid_chars)/len(df))*100,'%')

sequences_with_invalid_chars.to_csv('igm-autoinmune-PTMs.csv', index=False)

"""## **La siguiente pregunta es si el tipo de PTM varía en proporción entre IgM e IgG**
*Focus on autoimmune subset*
"""

ptms = [
  "AIB", "DEAM", "CITR", "PHOS", "SCM", "ACET", "NLeu", "GLYC",
  "AMID", "GLUC", "HYL", "METH", "OX", "BIOT"
]

ptm_dataframes = {}
for ptm in ptms:
    ptm_dataframes[ptm] = sequences_with_invalid_chars[
        sequences_with_invalid_chars['Epitope - Name'].str.contains(ptm, na=False)
    ]

# Display the first few rows of each PTM dataframe as an example
for ptm, df in ptm_dataframes.items():
    print(f"Data for PTM: {ptm}")
    display(df.head())

for i in ptms:
  print(i,len(ptm_dataframes[i]))

""" ### PTMs con IgG"""

df= pd.read_csv('igg-autoinmune.csv')

df= df[['Epitope - Name']]

# Función para encontrar secuencias con '+' o espacios
sequences_with_invalid_chars = df[df['Epitope - Name'].str.contains(r'[+\s]', na=False)]

# Mostrar las secuencias
print("Sequences with '+' or spaces:")
print(sequences_with_invalid_chars)

len(sequences_with_invalid_chars)

gptm_dataframes = {}
for ptm in ptms:
    gptm_dataframes[ptm] = sequences_with_invalid_chars[
        sequences_with_invalid_chars['Epitope - Name'].str.contains(ptm, na=False)
    ]

for ptm, df in gptm_dataframes.items():
    print(f"Data for PTM: {ptm}")
    display(df.head())

for i in gptm_dataframes:
  print(i,len(gptm_dataframes[i]))

import matplotlib.pyplot as plt
import pandas as pd

ptm_counts_igm = {ptm: len(df) for ptm, df in ptm_dataframes.items()}
ptm_counts_igg = {ptm: len(df) for ptm, df in gptm_dataframes.items()}

ptm_counts_df = pd.DataFrame({
    'PTM': list(ptm_counts_igm.keys()),
    'IgM': list(ptm_counts_igm.values()),
    'IgG': list(ptm_counts_igg.values())
})

ptm_counts_df.set_index('PTM').plot(kind='bar', figsize=(12, 6), color=['skyblue', 'salmon'])
plt.title('Frequency of PTMs in IgM and IgG Autoinmune Epitopes')
plt.xlabel('PTM')
plt.ylabel('Frequency')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Antibody Type')
plt.tight_layout()
plt.show()

"""<font color ='purple' > En lo que a patología autoinmune parece haber una distribución homogénea de PTMs para epítopos tanto en IgM como en IgG </font >"""